### ISSUE TITLE
UART pin description

### ISSUE THREAD

**Issue by TobiasPSP** [Jens3382/xy6020l#3]
Can‘t wait to start playing - thank you so much for sharing!

Could you share how the uart pins on the 6020 boards are assigned? I just see four pins on mine with no labels :-)

Many thanks!

**Comment by Jens3382** [comment]
I placed several pictures in description were the wiring is shown:
| Cable| XY6020L | Arduino ProMicro|
|----------------|-------------------------------|-----------------------------|
|Blue| GND |GND|
|Green| RX|TX |
|Yellow| TX|RX|
|Orange| 5V| RAW|

5V are at the PCB outside.

**Comment by TobiasPSP** [comment]
Awesome, greatly appreciated! Thank you Jens.
